version: "3.8"
services:
  auth:
    build:
      context: $AUTH_DIR_PATH
      target: development
    image: hugo/auth:1.0
    env_file: $AUTH_DIR_PATH/.env
    ports:
      - 8080:8080
    volumes:
      - $AUTH_DIR_PATH:/app
    depends_on:
      - pg
  # resources:
  #   build:
  #     context: ./packages/resource-server
  #     target: development
  #   image: hugo/resource:1.0
  #   env_file: ./packages/resource-server/.env
  #   ports:
  #     - 8081
  #   volumes:
  #     - ./packages/resource-server:/app
  #   depends_on:
  #     - pg
  pg:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
